### ISSUE TITLE
ReferenceError: Blockly is not defined - Angular 8

### ISSUE THREAD

**Issue by WieFel** [roroettg/ngx-blockly#1]
Hello,

I am facing an error when using the ngx-blockly module in my Angular 8.1.0 app (running with Node 10.16.0 and npm 6.9.0).
I exactly followed the setup steps described in the Github page but I get an error, which seems to arise within the file `ngx-blockly.js` (line 125).
The complete error message is:
```
ERROR ReferenceError: Blockly is not defined
    at NgxBlocklyComponent.ngAfterViewInit (ngx-blockly.js:125)
    at callProviderLifecycles (core.js:28194)
    at callElementProvidersLifecycles (core.js:28159)
    at callLifecycleHooksChildrenFirst (core.js:28141)
    at checkAndUpdateView (core.js:38380)
    at callViewAction (core.js:38736)
    at execComponentViewsAction (core.js:38664)
    at checkAndUpdateView (core.js:38377)
    at callViewAction (core.js:38736)
    at execComponentViewsAction (core.js:38664)
```

I already tried to install the <a href="https://www.npmjs.com/package/node-blockly">node-blockly</a> package and to add the import of Blockly to my component's module like so:
`import {Blockly} from "node-blockly;`
and
```
@NgModule({
	... ,
	imports: [
		... ,
                Blockly,
	]
})
```
But it doesn't seem to help.

Any other suggestions?

**Comment by roroettg** [comment]
Hi,

I think you might have forgotten to add the original blockly javascript-files to your scripts in your **angular.json**

``` typescript
"scripts": [
    "node_modules/ngx-blockly/scripts/blockly/blockly_compressed.js",
    "node_modules/ngx-blockly/scripts/blockly/blocks_compressed.js",
    "node_modules/ngx-blockly/scripts/blockly/python_compressed.js",
    "node_modules/ngx-blockly/scripts/blockly/msg/js/en.js",
]
`

**Comment by WieFel** [comment]
Thanks for the answer, but I already added exactly those 4 lines to my **angular.json** file, as it is described in the setup section.

Could there be any other reason for the problem?

**Comment by roroettg** [comment]
This is strange. I can only reproduce this error when the blockly javascript files are missing. 

Can you conform that these files are present at runtime?

**Comment by WieFel** [comment]
It seems that the problem is related to another error message, which is appearing before the error mentioned above:
```
blockly_compressed.js:143 Uncaught TypeError: Cannot read property 'navigator' of undefined
    at Object.goog.labs.userAgent.util.getNavigator_ (blockly_compressed.js:143)
    at Object.goog.labs.userAgent.util.getNativeUserAgentString_ (blockly_compressed.js:143)
    at blockly_compressed.js:143
```
Probably, the imports of the scripts fail because of this error, as **blockly_compressed.js** is the first imported script.
I tried to reproduce the error in a freshly setup Angular 8 project. But there, **ngx-angular** works without any problems.

However, I still can't find out what the problem is in this case. Have you maybe got an idea?

**Comment by roroettg** [comment]
Without further knowledge about your project I cannot really suggest anything else. You probably have already tried to clear your node_modules and to reinstall the package?

**Comment by WieFel** [comment]
Yes, I have tried that. Well, I keep trying and I will post the solution here if I find one.

**Comment by roroettg** [comment]
I will close this for now. If you can find a solution or a way for me to reproduce this issue, you can reopen it.

**Comment by davidTortosa** [comment]
I'm having the same error using 
Angular 8.2.14
Node 13.2.0
NPM 6.13.1

![Captura de pantalla 2020-02-19 a las 12 22 24](https://user-images.githubusercontent.com/36964300/74830016-84c15180-5312-11ea-8083-ed7b7b6895bd.png)

I followed the setup steps described in the [npm webpage](https://www.npmjs.com/package/ngx-blockly)

Adding the  javascript files
![image](https://user-images.githubusercontent.com/36964300/74830294-192bb400-5313-11ea-82b0-e23902d4eb49.png)

 the import at the corresponding module and the code to the component as the examples.

Thanks for the help
