### ISSUE TITLE
Custom Block - How to implement callback function that calls function in parent component

### ISSUE THREAD

**Issue by orlenkoo** [roroettg/ngx-blockly#101]
Hello, Thanks for reviewing this issue.

I would like to add call back function into custom block.
This call back function will fork function in parent component.

So here is the code.

![callback](https://user-images.githubusercontent.com/100224661/200982927-1dc41818-5998-4653-a6ae-afc9aec05fc8.png)

As you can see the image, the` functions.component.ts` includes` triggers.block.ts` as custom block.
I want to call `onCode` function in `functions.component.ts` from `toJavaScriptCode` function in `trigger.block.ts`.

Is that possible?

I am thinking about using args[0]...
But is it possible to accept function in args?

Thanks.

**Comment by orlenkoo** [comment]
So I tried this:

- functions.component.ts

` this.triggerBlocks = [new TriggerBlock("Device Response", null, [this.deviceResponse, this.onCode])];
`
- trigger.block.ts

```
export class TriggerBlock extends CustomBlock {
  deviceResponse = [];
  public onCode: any;
  constructor(type: string, blockMutator: BlockMutator, ...args: any[]) {
    // Add Mutator or further args if needed
    super(type, blockMutator, ...args);
    this.class = TriggerBlock;
    this.deviceResponse = this.args[0][0];
    this.onCode = this.args[0][1];
  }
```
  
  ```
defineBlock() {
  ....
  }
```

```
  toJavaScriptCode(block): string | any[] {
    console.log("TriggerBlock toJavaScriptCode");
    this.onCode("oncode function is working!!");
    return "Not implemented";
  }
```
It seems works well..

But Is this correct way?

Thanks.

**Comment by roroettg** [comment]
Hi,

you can definitely do it this way. 

May I ask why you need a callback into the parent component? Maybe I can give you a better answer, if I knew what you are trying to with it.
