### ISSUE TITLE
Generating code issue

### ISSUE THREAD

**Issue by sethrill** [roroettg/ngx-blockly#108]
Hey

I'm having some issues when trying to generate code from blocks. It seems that the javascriptCode event is not being triggered and neither are the other events. I've seen someone else with a similar issue and your response was to add generatorConfig on the element but it gives me an error whenever I add it. Am i missing something?

**Comment by roroettg** [comment]
Hi @sethrill,

which ngx-blockly version are you using and what error is shown on the console?
My current guess would be that you are using one of the RCs? Please update to a later version of ngx-blockly like 13.0.2, 14.0.0 or 15.0.0
