### ISSUE TITLE
how to use block in BlockMutator

### ISSUE THREAD

**Issue by candy4290** [roroettg/ngx-blockly#12]
Thanks for ngx-blockly;
in method mutationToDom,  i want to call method getFieldValue like official example.
I have an idea:
ngx-blockly.component.ts:
 mutationToDom: function () {
       return this.blockInstance.blockMutator.mutationToDom(this);
},
block-mutator.ts:
public abstract mutationToDom(block: any);

have any better idea??

And i send a  'pull request' yesterday to let BlockMutator support decompose and compose, can you help me?

**Comment by candy4290** [comment]
I have send a 'pull request' to include my idea, hope to receive your reply.

**Comment by roroettg** [comment]
Hi,
thanks for your contribution to ngx-blockly. Mutators have been a thing on my To-Do list for awhile now. I will have a look at your PR as soon as I have some spare time.

**Comment by candy4290** [comment]
ok,thanks.

**Comment by davidcunningham** [comment]
Are there any more examples of using mutators? The custom one posted is very basic and doesn't get into things like adding new blocks/inputs/etc into an existing block and mutating it.

**Comment by roroettg** [comment]
Hi,
it is possible to create mutators quite similar to the way described in the blockly documentation. Since the documentation does not go into that much details as well, it is best to look at already implemented blocks.

https://github.com/google/blockly/blob/master/blocks/math.js
https://github.com/google/blockly/blob/master/blocks/

I hope this can help you.

**Comment by SvenJacobsUni** [comment]
Hey, thank you so much for your work!
I got the plusminus mutator (https://www.npmjs.com/package/@blockly/block-plus-minus) working for my (quite basic) custom block. Maybe this method can help some people in the future to create their own mutators.
- (install the plus-minus package -> see above link)
- create a mutator javascript ( i pretty much took their code for lists and changed it) -> see attachment
- enable the mutator for your block: _this.block.jsonInit({mutator: "from_mutator",})_; and change codegenerator -> see attachment
- In blockly.component.ts you just import the mutator javascript: _import * as FromMutator from './mutators/FromMutator';_
and call it : _ngOnInit(): void {FromMutator; }_

Attachment: [plusminus.zip](https://github.com/roroettg/ngx-blockly/files/5144677/plusminus.zip)
