### ISSUE TITLE
readme update required

### ISSUE THREAD

**Issue by vinayakbkulkarni** [roroettg/ngx-blockly#14]
I am trying to build angular app using this demo.
I do not see the files like node_modules/ngx-blockly/scripts/blockly/blockly_compressed.js
Readme seems to be not updated. Please check.
Thanks

**Comment by roroettg** [comment]
The RC for version 1.0.0 was wrongly tagged as latest. With this version these files wont be needed anymore as https://www.npmjs.com/package/blockly will be used. I have not found time to update the docs yet. 

Please use 0.0.45 until I have updated the docs.
