### ISSUE TITLE
Call function when clicking on FieldImage

### ISSUE THREAD

**Issue by labozilla** [roroettg/ngx-blockly#16]
Hello,

I am trying to call a function when clicking FieldImage in a CustomBlock.
I tried to use the setOnClickHandler method and pass the function, however, the function is called by dragging and dropping the block, not by clicking on the image.
I also tried to pass the function in the FieldImage constructor, with the same result.
Is there another way to do this?

**Comment by roroettg** [comment]
Hi,

I did a quick test and passing a function through the FieldImage constructor works fine. Maybe you can show your code for further analysis.

Docs:

https://developers.google.com/blockly/reference/js/Blockly.FieldImage

Example:
``` typescript
    public defineBlock() {
        this.block.appendDummyInput()
            .appendField(this.type)
            .appendField(new Blockly.FieldImage('assets/dummy.png', 50, 50, 'dummy', this.doSth));
        this.block.setOutput(true, 'Input');
        this.block.setColour(30);
        this.block.setTooltip('');
        this.block.setHelpUrl('');
    }

    public doSth() {
        console.log('fu');
    }
```

**Comment by labozilla** [comment]
Thanks for the feedback.

**Worked perfectly.**
In my code I was putting parentheses at the end of the function call. Without parentheses it works very well.

**it works:**
.appendField(new Blockly.FieldImage('assets/dummy.png', 50, 50, 'dummy', this.doSth)); 

**not work**
.appendField(new Blockly.FieldImage('assets/dummy.png', 50, 50, 'dummy', this.doSth()));
