### ISSUE TITLE
The component's content overflows the parent div

### ISSUE THREAD

**Issue by yonderTech** [roroettg/ngx-blockly#25]
Hi there,

Here's my template set up:

```
<div style="height: 600px; width: 600px;">
  <ng-container #blocklyContainer></ng-container>
</div>
```

And in my component

```
@ViewChild("blocklyContainer", { read: ViewContainerRef }) blocklyContainer: ViewContainerRef;

let ngxBlockyFactory = this.resolver.resolveComponentFactory(NgxBlocklyComponent);

          this.ngxToolboxBuilder.nodes = [
          LOGIC_CATEGORY,
          LOOP_CATEGORY,
          MATH_CATEGORY,
          TEXT_CATEGORY,
          LISTS_CATEGORY,
          FUNCTIONS_CATEGORY,
          new Separator() 
          //my custom blocks here....
        ];

        this.config.toolbox = this.ngxToolboxBuilder.build();

        let blockly = this.blocklyContainer.createComponent(ngxBlockyFactory);
        blockly.instance["config"] = this.config;
        blockly.instance["customBlocks"] = this.customBlocks;
        blockly.instance["generatorConfig"] = this.generatorConfig;
        blockly.instance["javascriptCode"].subscribe((e) => {
          this.onCode(e);
        });
```

As you can see, I create the `ngx-blocky` component dynamically, main reason being that my custom blocks can be different, depending on application context.

The problem is that the resulting workspace overflows the div in which I set the size (600x600).

I can see in the inspector, there's a div being produced that matches the correct size (with id #blockly-wrapper) and also ngx-blockly has the correct dimensions.

But the child of #blockly-wrapper which is #blocky, doesn't, it's much bigger.

I've tried this styling

```
ngx-blockly {
  position: absolute;
  width: 100%;
  height: 100%;
}
```

But then all the div's ignore the 600x600 dimensions...

Any way to fix that ?

Thanks

**Comment by roroettg** [comment]
Hi,
I haven't tested it for your case. But my guess would be, that a simple `position: relative` in your outer div should solve the problem?

**Comment by roroettg** [comment]
Seems to be solved.
Reopen if you need further help.

**Comment by yonderTech** [comment]
> Hi,
> I haven't tested it for your case. But my guess would be, that a simple `position: relative` in your outer div should solve the problem?

That worked, thanks.
