### ISSUE TITLE
Add custom block with another block

### ISSUE THREAD

**Issue by ctwong-adft** [roroettg/ngx-blockly#26]
I having some issue on the custom block when connected to another block. For example, the custom block that I created have the function "x set to" is connected with math number block "2" but the javascript code is unable to show the correct format. It only show "var x;" but it should show "x=2;".

**Comment by roroettg** [comment]
Could you provide your code or more details?

So far I can only tell you that code generation needs to be handled by yourself.

**Comment by ctwong-adft** [comment]
If I want to read the input from other block ?

**Comment by ctwong-adft** [comment]
This issue is solved.
