### ISSUE TITLE
Issue translating values and statements

### ISSUE THREAD

**Issue by mrlujanero** [roroettg/ngx-blockly#27]
Hi! First of all, thanks for your efforts creating this library. It's really useful.

I've been working with it and defined my own custom blocks and now I'm working on the traslations. Everything was going well with simple blocks that only had fields. However, more complex blocks that have statements and value inputs seem impossible to translate.

I've been reading the official documentation about Blockly and I've found this two methods: statementToCode and valueToCode, but I'm not sure on how tu use them in angular.

Could you help me with that?

Many thanks in advance.

Regards.

**Comment by roroettg** [comment]
Hi,

thanks for your kind words.

You can use these two methods pretty similar to what is written in the documentation.

https://developers.google.com/blockly/reference/js/Blockly.Generator#statementToCode
https://developers.google.com/blockly/reference/js/Blockly.Generator#valueToCode

```typescript
# Blockly needs to be declared
declare var Blockly: any;

# Use this in your code generations step, change accordingly
Blockly.Python.statementToCode(block, name);

Blockly.Python.valueToCode(block, name, outerOrder);
```

**Comment by mrlujanero** [comment]
Yes! That worked! I'll close this thread :)

Many thanks.
