### ISSUE TITLE
ERROR in Symbol NgxBlocklyComponent

### ISSUE THREAD

**Issue by hamilton-lima** [roroettg/ngx-blockly#30]
Steps to reproduce
- Create a new angular application
- Follow the readme steps
- ng serve the application

Result
`ERROR in Symbol NgxBlocklyComponent declared in /home/ubuntu/source/block-playground/node_modules/ngx-blockly/lib/ngx-blockly/ngx-blockly.component.d.ts is not exported from ngx-blockly/lib/ngx-blockly.module (import into /home/ubuntu/source/block-playground/src/app/app.component.ts)`

Tried with version 10.0.1 and 10.0.2

**Comment by roroettg** [comment]
I cannot really reproduce this and found only a smaller error in the README which falsely stated that 
```
<ngx-blockly [config]="config"></ngx-blockly>
```
belongs to app.component.ts and not app.component.html

Does this fix your error?

If not please provide more of your code for further debugging.

**Comment by hamilton-lima** [comment]
I will upload the test Application I created

**Comment by hamilton-lima** [comment]
Found the issue! auto import was adding this 
`import { NgxBlocklyModule } from 'ngx-blockly/lib/ngx-blockly.module';`

Instead of 
`import { NgxBlocklyModule } from 'ngx-blockly';`

Now is working fine, test project here: https://github.com/hamilton-lima/blockly-sandbox

Thanks for looking into it!
cheers
