### ISSUE TITLE
override existing code generator

### ISSUE THREAD

**Issue by fjaen** [roroettg/ngx-blockly#39]
Hello,
is there a way to override the current behavior of the Blockly.Lua['procedures_defreturn'] function?

I would like to implement some extra actions when this function is called
Thank you very much for your help

**Comment by roroettg** [comment]
Hi,

you can probably just do it like this.

```typescript
declare var Blockly: any; // if not already declared

Blockly.Lua['procedures_defreturn'] = (block) => {
    console.log('Foo');
    return 'ReturnValue';
}
```
Please change these definitions as early as possible, you could use the module definition for example.

**Comment by fjaen** [comment]
Hi, 
Thank you very much for your quick answer, I tried this but I got a compilation error
Failed to compile.

src/app/app.module.ts:56:40 - error TS7006: Parameter 'block' implicitly has an 'any' type.

56 Blockly.Lua['procedures_defreturn'] = (block) => {

Thanks again for your help

**Comment by roroettg** [comment]
This error probably occurs because of a strict compiler configuration.

One option would be to set ` "noImplicitAny": false` in your tsconfig.json or you can change the code like this

` Blockly.Lua['procedures_defreturn'] = (block: any) => {
`

**Comment by fjaen** [comment]
Thanks so much. This indeed solved the problem.
I still have to find out how to get rid of the comment added to functions
"-- Describe this function" which is still added despite I provide my own override function.
BTW, Thank you very much for implementing this wrapper. I find it very useful.
