### ISSUE TITLE
Bug when using FieldTextInput or FieldDropdown

### ISSUE THREAD

**Issue by thedjdoorn** [roroettg/ngx-blockly#42]
When I want to use an input or dropdown in a custom block, it selects and won't unselect when I try to use the input or dropdown. When I do, it prints the following error message:

> ERROR TypeError: a is undefined
>     render blockly_compressed.js:564
>     showEditor_ blockly_compressed.js:1126
>     showEditor blockly_compressed.js:491
>     doFieldClick_ blockly_compressed.js:473
>     handleUp blockly_compressed.js:467
>     handleUp blockly_compressed.js:701
>     h blockly_compressed.js:854
>     Angular 14
>     bindEvent_ blockly_compressed.js:856
>     bindDocumentEvents_ blockly_compressed.js:791
>     init_ blockly_compressed.js:789
>     inject blockly_compressed.js:782
>     ngAfterViewInit ngx-blockly.js:96
>     Angular 25
>     RxJS 5
>     Angular 19
>     RxJS 5
>     Angular 15
> core.js:6140
> 
> Tried to start the same gesture twice. 2 blockly_compressed.js:780:261
> 
> Trying to end a gesture recursively. blockly_compressed.js:467:92

This is what my `defineBlock` code looks like:

```ts
  defineBlock(): any {
    // set name
    this.block.appendValueInput('FIRST')
    this.block.appendDummyInput().appendField(new Blockly.FieldDropdown([
      ["==", "EQ"],
      ["!=", "NE"],
      [">", "GT"],
      [">=", "GTE"],
      ["<", "LT"],
      ["<=", "LTE"]
    ]), 'FUNCTION');
    this.block.appendValueInput('SECOND')
    //set content
    this.block.setColour(20)
    this.block.setTooltip('Compare two values')
    this.block.setHelpUrl('')
    this.block.setPreviousStatement(true)
    this.block.setNextStatement(true)
  }
```

**Comment by roroettg** [comment]
Hello,

I checked your code and could not reproduce the issue. Could you provide more of your code? Which ngx-blockly version are you using?

Here is the CustomBlock with your code.


```typescript
import { BlockMutator, CustomBlock } from 'ngx-blockly';

declare var Blockly: any;

export class ExampleBlock extends CustomBlock {

    constructor(block: any, blockMutator: BlockMutator) {
        super('example_block', block, blockMutator);
        this.class = ExampleBlock;
    }

    public defineBlock() {
        this.block.appendValueInput('FIRST')
        this.block.appendDummyInput().appendField(new Blockly.FieldDropdown([
            ["==", "EQ"],
            ["!=", "NE"],
            [">", "GT"],
            [">=", "GTE"],
            ["<", "LT"],
            ["<=", "LTE"]
        ]), 'FUNCTION');
        this.block.appendValueInput('SECOND')
        //set content
        this.block.setColour(20)
        this.block.setTooltip('Compare two values')
        this.block.setHelpUrl('')
        this.block.setPreviousStatement(true)
        this.block.setNextStatement(true)
    }

    public toPythonCode(block: ExampleBlock): string | any[] {
        return '';
    }
}
```

**Comment by thedjdoorn** [comment]
Oops, apparently I wasn't supposed to `import * as Blockly from "blockly";`.
It works now, thanks for the support!
