### ISSUE TITLE
How to add new Generator?

### ISSUE THREAD

**Issue by pptyasar** [roroettg/ngx-blockly#43]
I am able to add new generator with js code like below code

` playground.addGenerator('SAS', Blockly.SAS)`

But I am not able to find playground object in this library

https://blocklycodelabs.dev/codelabs/custom-generator/index.html?index=..%2F..index#2

**Comment by roroettg** [comment]
Hi,
playground is not part of the blockly library. It is a wrapper created in codelabs to quickly create a blockly workspace with default values.

https://github.com/google/blockly-samples/blob/e49fc846eb121df9960c38ae62877839db91c148/plugins/dev-tools/src/playground/index.js#L83

I am not sure how much of their tutorial is applicable to ngx-blockly. 

If you want to add a new generator to ngx-blockly, you should probably take a look at how blockly does it for the already existing generators.

https://github.com/google/blockly/tree/master/generators
