### ISSUE TITLE
[Help want] Variable

### ISSUE THREAD

**Issue by goragodp** [roroettg/ngx-blockly#46]
I'd like to create a variable before render a blockly workspace. 
I look around in Google Blockly document and I found 
```javascript
Blockly.Variables.createVariableButtonHandler(button.getTargetWorkspace(), null, 'panda');
```
But I'm not sure how to implement it with your lib

**Comment by roroettg** [comment]
Since you can access Blockly by `declare var Blockly: any;`  you can use the method as you described.

**Comment by roroettg** [comment]
Also trying to create a Variable without workspace is not possible.

Please not that `Blockly.Variables.createVariableButtonHandler()` is deprecated use `Blockly.Variables.createVariable()`.

But with your description it seems more likely that you want to add variables without opening a dialog for user input. If that is the case you probably want to use: https://developers.google.com/blockly/reference/js/Blockly.Workspace#createVariable

**Comment by goragodp** [comment]
Thank for your answer, I'm kinda newbie in angular.
I try to use your mention function and the output indicate that Blockly has undefine type

> Since you can access Blockly by `declare var Blockly: any;` you can use the method as you described.

I've declared  `declare var Blockly:any;` as you suggested.
I try to add an variable in constructor and this is my code
```javascript
 declare var Blockly:any;
...
...
  constructor(ngxToolboxBuilder: NgxToolboxBuilderService) {
    ngxToolboxBuilder.nodes = [
        LOGIC_CATEGORY,
        LOOP_CATEGORY,
        MATH_CATEGORY,
        TEXT_CATEGORY,
        LISTS_CATEGORY,
        VARIABLES_CATEGORY,
        new Category('Temi Skill', '#FF21FF',this.customBlocks, null)
    ];
    Blockly.Variable.createVariable("test");
    this.config.toolbox = ngxToolboxBuilder.build();
  }
```

**Comment by roroettg** [comment]
Please take a close look at the method signatures.

https://developers.google.com/blockly/reference/js/Blockly.Variables#.createVariable

You will need an existing workspace to add variables to it.

Here is a working example:

``` html
<ngx-blockly
    #blockly
    [config]="config"
    [readonly]="readonly"
    [generatorConfig]="generatorConfig"
    [customBlocks]="customBlocks">
</ngx-blockly>
```
**Please be aware of the #blockly**
```
...

declare var Blockly: any;

@Component({
    selector: 'app-root',
    templateUrl: './app.component.html',
    styleUrls: ['./app.component.scss']
})
export class AppComponent implements AfterViewInit {

    public readonly = false;

    public customBlocks = [
        new ExampleBlock(null, new ExampleMutator('example_mutator'))
    ];

    public config: any = {
        scrollbars: true,
        trashcan: true,
        plugins: {
            'toolbox': NgxBlocklyToolbox
        }
    };

    @ViewChild('blockly') blocklyComponent: NgxBlocklyComponent;

    public generatorConfig: NgxBlocklyGeneratorConfig = {
        dart: true,
        javascript: true,
        lua: true,
        php: true,
        python: true,
    };

    constructor(ngxToolboxBuilder: NgxToolboxBuilderService) {
        ngxToolboxBuilder.nodes = [
            LOGIC_CATEGORY,
            LOOP_CATEGORY,
            MATH_CATEGORY,
            TEXT_CATEGORY,
            LISTS_CATEGORY,
            COLOUR_CATEGORY,
            new Separator(),
            VARIABLES_CATEGORY,
            FUNCTIONS_CATEGORY
        ];
        this.config.toolbox = ngxToolboxBuilder.build();
    }

    ngAfterViewInit(): void {
        // With prompt
        Blockly.Variables.createVariable(this.blocklyComponent.workspace, null, 'test');
        // Directly add variable
        this.blocklyComponent.workspace.createVariable('test', null, null);
    }
}

```
**Notice the Viewchild variable and that the workspace can only be accessed after AfterViewInit**

Workspace can be accessed only after it is rendered. If you are not familar with the angular life cycle please read https://angular.io/guide/lifecycle-hooks first.

**Comment by goragodp** [comment]
It's really work!!!!!
Thank for your help and explanation! It's clearer than any material I have been search so far
