### ISSUE TITLE
Problem with readonly flag

### ISSUE THREAD

**Issue by timadevelop** [roroettg/ngx-blockly#5]
Shouldn't the `readonly` flag be `readOnly` in `NgxBlocklyConfig` type declaration?

`readOnly` option is **case-sensitive** in Blockly library, but `NgxBlocklyConfig` type declaration expects `readonly` (lowercase)

[blockly docs ref](https://developers.google.com/blockly/guides/get-started/web)

**Comment by roroettg** [comment]
Sorry for the delayed answer.

You are totally right and I will fix this asap.
