### ISSUE TITLE
DropDownField Generator

### ISSUE THREAD

**Issue by fjaen** [roroettg/ngx-blockly#52]
Hi,
I have a custom block with a drowpdown field and a generator like this

this.block.appendDummyInput().appendField(new Blockly.FieldDropdown(this.populateOptions), "OBJECTS");

However in my populateOptions function I would like to access properties of my custom block using "this" 

populateOptions(){
return this.options;
}
However when I execute the code "this" is of type Blockly.Field; I tried to do something like

 populateOptions(){
        var b:any=this;
        var c=b.getSourceBlock();
        ...
    }
but I get a null value on c.
Do you know how to get a reference to the CustomBlock object that contains the dropdown field?
Many thanks in advance
J.

**Comment by roroettg** [comment]
Hi,
you could probably do something like this to keep the context in your function.

```
this.block.appendDummyInput().appendField(new Blockly.FieldDropdown(this.populateOptions()), "OBJECTS");

public populateOptions() {
   return () => {
        const dropdown = [];
        // code creating dropdown
        // this should still point to your CustomBlock
        return dropdown;
        
   }
}
```

**Comment by fjaen** [comment]
Thanks a lot for your quick answer. I made a simple test:

populateOptions(){
        return () => {
            return [['self','self'],['event_source','event_source']];
       }        
    }
and I get this error "TypeError: FieldDropdown options must be an array". The same occurs with 
         const dropdown = [];
        // code creating dropdown
        // this should still point to your CustomBlock
        return dropdown;
It seems the body of the lambda expression is not executed. A breakpoint inside this  section is never reached.
Thank you very much again for any help you may provide

**Comment by fjaen** [comment]
I found a workaround to this problem by using a method on my CustomBlock class that updates internally its state so thar the collection of options is changed before the FieldDropDown field is rendered

 auxBlock.blockInstance.setConcreteInstancesOnly(true);
 auxBlock.initSvg();
 auxBlock.render(); 

and then
     setConcreteInstancesOnly(mode:boolean){
         this.mode=mode;
         const field = this.block.getField("GAME_OBJECTS");
         if (this.mode)
         field.menuGenerator_=... //generating options here for mode==true             
         else field.menuGenerator_= ... //generating options here for mode ==false
         field.setValue(field.getOptions()[0][1]);
         field.forceRerender();
     }

Thank you very much anyway for your help
