### ISSUE TITLE
Allow the toolbox to scroll

### ISSUE THREAD

**Issue by hopper01** [roroettg/ngx-blockly#58]
Refer to Issue https://github.com/google/blockly/pull/1319#issue-141386963

Reply from author: 
https://github.com/google/blockly/pull/1319#issuecomment-864201167

**Comment by roroettg** [comment]
Hi,

thank you for reporting this bug.

With 10.1.4 this fixed. Feel free to reopen if this issue is not fixed.

**Comment by hopper01** [comment]
> Hi,
> 
> thank you for reporting this bug.
> 
> With 10.1.4 this fixed. Feel free to reopen if this issue is not fixed.

Okay, Thanks @roroettg
