### ISSUE TITLE
Pass parameter to CustomBlock

### ISSUE THREAD

**Issue by labozilla** [roroettg/ngx-blockly#6]
Hello, how are you?

First of all I would like to congratulate you on working with ngx-blockly.
I have a question: I would like to send a parameter to CustomBlock.
For example, a custom block with a dynamic image.
I did a test by passing a parameter to the CustomBlock constructor, the value for the parameter arrives in the constructor, however, when clicking on the block in toolbox the constructor is called again without this parameter.
I marked the changes
How can I do this?
Thanks.

......
export class TestBlock extends CustomBlock {
   **nameImage: string;**
    constructor(type: string, block: any, blockMutator: BlockMutator, **nameImage: string)** {
        super(type, block, blockMutator);
        this.class = TestBlock;
        **this.nameImage = nameImage;**
    }

.......
.appendField(new Blockly.FieldImage(**this.nameImage**, 50, 50, '*'))

**Comment by roroettg** [comment]
Hi,

thanks for using ngx-blockly.

So far there was no good way of doing this. I have come up with a solution, which might change in the future, but for now it will do.

With ad5813e29741a63902ddce24f24cb63323de183a you should now be able to do following:

```typescript
new TestBlock('test', null, null, 'assets/dummy.png', 'Further Variable');
```
```typescript
export class TestBlock extends CustomBlock {
    public image: string;

    constructor(type: string, block: any, blockMutator: BlockMutator, ...args: any[]) {
        super(type, block, blockMutator, ...args);
        this.class = TestBlock;
    }

    defineBlock() {
        this.block.appendDummyInput()
            .appendField(this.type)
            .appendField(new Blockly.FieldImage(this.args[0], 50, 50, '*')); // this.args[0] === 'assets/dummy.png',
        this.block.setOutput(true, 'Input');
        this.block.setColour(30);
        this.block.setTooltip('');
        this.block.setHelpUrl('');
    }
}
````

**Comment by labozilla** [comment]
Everything working now. thanks.
