### ISSUE TITLE
Workspace disappears when status bar appears on window. 

### ISSUE THREAD

**Issue by hopper01** [roroettg/ngx-blockly#60]
I  am using blockly-workspace on fullscreen and when the status bar of chrome appears at the bottom and the workspace (where I drag block-codes) gets all white (it disables) . And when the status bar is removed it reappears(enable).

<img width="719" alt="Screenshot 2021-07-05 at 1 48 18 PM" src="https://user-images.githubusercontent.com/56765404/124440199-009d2c00-dd98-11eb-8129-49466584fb50.png">

<img width="719" alt="Screenshot 2021-07-05 at 1 33 06 PM" src="https://user-images.githubusercontent.com/56765404/124439138-ab144f80-dd96-11eb-9193-c2e8e780c561.png">

**Comment by ankit18singh** [comment]
+1

**Comment by roroettg** [comment]
Hi,
I cannot really reproduce this issue. 

What does fullscreen mean? Chrome in full screen oder just using 100% width and height?
What does trigger the statusbar in your program?
Which version of ngx-blockly are you using?
Could you provide code or a small example where I see the issue?

**Comment by hopper01** [comment]
> Hi,
> I cannot really reproduce this issue.
> 
> What does fullscreen mean? Chrome in full screen oder just using 100% width and height?
> What does trigger the statusbar in your program?
> Which version of ngx-blockly are you using?
> Could you provide code or a small example where I see the issue?

yes, by fullscreen I meant 100% width and height.
The status bar appears when I download my code.
Version 10.0.16

**Comment by roroettg** [comment]
Still cannot reproduce your issue. I would suggest to use the latest ngx-blockly version 10.1.4.

But my guess would be that the error is somewhere in your download mechanism.  

Do you see any logs on the developer console?
Could you provide a code example, how you download the code?

**Comment by hopper01** [comment]
To download the code, I place a div over the workspace (change view of the app or like a side-panel over it ) where the download button is placed.  
This issue comes in the above mentioned case . Somehow, the workspace unmounts and when I refresh the page or even when I tigger the workspace again (like expanding the sensors menu or remove the status bar) it comes back.

**Comment by roroettg** [comment]
Still need more information to reproduce this.

Please provide error logs from the console, source code or an example.

**Comment by hopper01** [comment]
> Still need more information to reproduce this.
> 
> Please provide error logs from the console, source code or an example.

There are no error logs on the console, I cannot disclose the code, for now, I have fixed the issue with , 'Resize' event of the window, and it solves the problem, but why it is happening is still a point.
