### ISSUE TITLE
Missed "scripts" and "services" folder during npm package download from version 10.1.3

### ISSUE THREAD

**Issue by Amboryus** [roroettg/ngx-blockly#68]
Good Morning,
In the past few days the directories "scripts" and "services" were no longer contained in the "node_modules/ngx-blockly" package with version 10.1.3. Yesterday around 2 p.m. these were available again. I cannot explain the behavior for versions that have existed for a long time. I was looking for a way to inform you about this. Currently that is no longer a problem. Everything works fine now. But you have to know this what happend.

Greetings from Germay (Lübeck) ;-)

**Comment by kstanitzok** [comment]
I cant access the "scripts"-folder currently because it is missing for me.

**Comment by Amboryus** [comment]
This screenshot is based on a fresh npm "ngx-blockly@10.1.3"

![image](https://user-images.githubusercontent.com/17248709/133588232-f7f6b074-8d80-408e-ad3c-ebb50d172915.png)

**Comment by roroettg** [comment]
Hello,

I think you two ran into an issue with semantic versioning.

If you are using ^10.1.3 in your package.json, it will use 10.2.0 which contains the refactored ngx-blockly, where scripts and services do not exist anymore. Please view the updated documentation.

If you do not want to update to the latest ngx-blockly, please pin your version to 10.1.3 oder 10.1.4

**Comment by roroettg** [comment]
If this issue is still relevant, feel free to reopen. I will close this for now.
