### ISSUE TITLE
Unknown block types

### ISSUE THREAD

**Issue by NCC1701M** [roroettg/ngx-blockly#69]
# Behaviour
When I try to open one of the build in categories I get an error, that the block type is unknown e.g.
```
ERROR TypeError: Unknown block type: math_number
```

```
ERROR TypeError: Unknown block type: controls_repeat_ext
```

```
ERROR TypeError: Unknown block type: controls_if
```

# Setup
I build the toolbox as follows:
```typescript
const config: NgxBlocklyConfig = {
	generators: [
		NgxBlocklyGenerator.JAVASCRIPT
	],
	toolbox: "",
	trashcan: true
};

this.customBlocks = [
	// getDefaultBlocks are static methods which return all the blocks for the category
	...FirstCustomCategory.getDefaultBlocks(),
	...SecondCustomCategory.getDefaultBlocks()
];

const workspace = new Blockly.WorkspaceSvg(new Blockly.Options({}));
const toolbox = new NgxBlocklyToolbox(workspace);

toolbox.nodes = [
	new FirstCustomCategory(),
	new SecondCustomCategory(),
	new Separator(),
	LOGIC_CATEGORY,
	LOOP_CATEGORY,
	MATH_CATEGORY,
	TEXT_CATEGORY,
	LISTS_CATEGORY,
	VARIABLES_CATEGORY
];
this.config.toolbox = toolbox.toXML();
```

```html
<ngx-blockly *ngIf="showEditor"
             [config]="config"
             [customBlocks]="customBlocks"
             (workspaceChange)="onWorkspaceChanged($event)"
             (workspaceCreate)="onWorkspaceCreated($event)"></ngx-blockly>
```

# Hints
It works fine for all custom categories / blocks and also for the `VARIABLES_CATEGORY`. But within the `VARIABLES_CATEGORY` have the button `Create Variable...` and when I click on it the input dialog opens but after entering a variable name, nothing happens, now variable block appears and no error message.

# Information
Package | Version
---------|---------
Angular | 11
Angular Material | 11
ngx-blockly version | 11.0.2

**Comment by roroettg** [comment]
Hello,

you probably have forgotten to import "blockly/blocks"; . Otherwise blocklys default blocks will be not initialized. I would suggest to import it as early as possible.

Here is a basic example:

https://roroettg.github.io/ngx-blockly/basic/index.html

**Comment by NCC1701M** [comment]
> you probably have forgotten to import "blockly/blocks"; . Otherwise blocklys default blocks will be not initialized. I would suggest to import it as early as possible.

I had the import statement already in the component file. I've moved the import to the module file but there was no change. Still get the error

**Comment by NCC1701M** [comment]
I've found the solution. I had still bkloky 5 installed instead of version 6. Updating to `blockly@^6.20210701.0` fixed the issue.
