### ISSUE TITLE
Add custom block array

### ISSUE THREAD

**Issue by rochap01** [roroettg/ngx-blockly#7]
Hello,
How could I add customBlock dynamically?
Something like the example below.
I tried to use a loop and add to the CustomBlock array, but it is not displayed in the toolbox.
Any idea?

```
this.array.forEach((item) => {
          this.customBlocks.push(new TestBlock('test', null, null));
  });
```

**Comment by roroettg** [comment]
Hi,

first of all you should have a look at NgxToolboxBuilderService. There you can see how the toolbox is created. It is important that after changes you need to rebuild the toolbox.

Maybe this code snippet makes it clearer
```
ngxToolboxBuilder.nodes = this.customBlocks;
for (let i = 0; i < 5; i++) {
    this.customBlocks.push(new TestBlock('test' + i, null, null));
}
this.config.toolbox = ngxToolboxBuilder.build();
```
