### ISSUE TITLE
Blockly 7 update ?

### ISSUE THREAD

**Issue by vanackej** [roroettg/ngx-blockly#76]
Hi,

I'm very interested in blockly 7 support, that brings major updates, but also a lot of breaking changes.
Is there any plan to update to blockly 7 anytime soon ?

I personnaly tried to patch the library, but didn't succeed yet. I can try to initiate something or contribute to the effort if needed.

Thanks !

**Comment by roroettg** [comment]
Hi,

I will try to integrate the latest blockly release as soon as possible. Unfortunately the typings are really broken at the moment as you probably have noticed. I am hoping for another patch for blocky 7.

If you want to start making progress here, feel free to make a PR.

**Comment by vanackej** [comment]
Ok, if feel a little less stupid now. I had the impression typescript
support was messy for now, but wasn't sure.
Let's monitor Blockly updates and wait for better typescript support,
hopefully soon :-)

**Comment by IBlackI** [comment]
Related issue regarding the broken types:
https://github.com/google/blockly/issues/5864

**Comment by vanackej** [comment]
To keep issue open, until blockly upstream issue is fixed

**Comment by IBlackI** [comment]
Upstream issue still open.

**Comment by roroettg** [comment]
With Blockly v9.0.0 issues seems to be fixed.

I released RC for Angular 13 and 14, feel free to test them.
