### ISSUE TITLE
ERROR TypeError: Unknown block type: controls_if

### ISSUE THREAD

**Issue by PabliyoCR** [roroettg/ngx-blockly#77]
How can I solve this error? Thanks

**Comment by roroettg** [comment]
Hi, 

you probably need to import the default blocks anywhere in your code with this code  `import 'blockly/blocks';`.

To avoid any further errors you should import them as early as possible. I would suggest to import it in your module file.

**Comment by PabliyoCR** [comment]
@roroettg  scope fix this by importing into the module
import 'ngx-blockly/node_modules/blockly/blocks';

**Comment by roroettg** [comment]
Since blockly is a peer dependency this should not be necessary.

This import is not part of this lib, because not everybody has the need for the standardblocks. 

For more information please check the npm package of blockly
https://www.npmjs.com/package/blockly
