### ISSUE TITLE
Migrating from ngx-blockly 10.0.16 to 12.0.5

### ISSUE THREAD

**Issue by fjaen** [roroettg/ngx-blockly#81]
Hi,
I am migrating my code from version 10.0.16 to 12.0.5 and I got several errors.

1) import { ..., NgxToolboxBuilderService, ... } from 'ngx-blockly'; and I get an error saying that ngx-blockly"' has no exported member 'NgxToolboxBuilderService' 

2) public config: NgxBlocklyConfig = {
    scrollbars: true,
    trashcan: true,
    grid: {
      spacing: 50,
      length: 1,
      colour: "blue",
      snap: true
    },
    plugins: {
        toolbox: NgxBlocklyToolbox
    }
  }
and I get an error saying that scrollbars does not exist in type 'NgxBlocklyConfig' 

3) new Category('Game Objects', '#FF00FF',[],this.gameobjectcategories) and I get an error a parameter of type Category[] cannot be assigned to a parameter of type string

Any help with these errors would be much appreciated
J.

**Comment by roroettg** [comment]
Hi,

as lot has changed since then, unfortunately the docs are not up to date.

1. NgxToolboxBuilderService is obsolete.

Do it like this
```typescript
        const workspace = new Blockly.WorkspaceSvg(new Blockly.Options({}));
        const toolbox: NgxBlocklyToolbox = new NgxBlocklyToolbox(workspace);
        toolbox.nodes = [
            LOGIC_CATEGORY,
            new Category('bla', '#ff0000', [...this.customBlocks, this.button, this.label]),
            LOOP_CATEGORY,
            MATH_CATEGORY,
            TEXT_CATEGORY,
            LISTS_CATEGORY,
            COLOUR_CATEGORY,
            new Separator(),
            VARIABLES_CATEGORY,
            FUNCTIONS_CATEGORY,
            LOGIC_CATEGORY,
            new Category('bla', '#ff0000', [...this.customBlocks, this.button, this.label]),
            LOOP_CATEGORY,
            MATH_CATEGORY,
            TEXT_CATEGORY,
            LISTS_CATEGORY,
            COLOUR_CATEGORY,
            new Separator(),
            VARIABLES_CATEGORY,
            FUNCTIONS_CATEGORY,
            LOGIC_CATEGORY,
            new Category('bla', '#ff0000', [...this.customBlocks, this.button, this.label]),
            LOOP_CATEGORY,
            MATH_CATEGORY,
            TEXT_CATEGORY,
            LISTS_CATEGORY,
            COLOUR_CATEGORY,
            new Separator(),
            VARIABLES_CATEGORY,
            FUNCTIONS_CATEGORY
        ];
        this.config.toolbox = toolbox.toXML();
```

2. The blockly config has been changed
```typescript
 public config: NgxBlocklyConfig = {
        ...
        move: {
            scrollbars: true,
            wheel: true
        }
```

3. Category constructor has been changed

```
new Category('bla', '#ff0000', [CustomBlockA, CustomBlockB]);
```

**Comment by fjaen** [comment]
Thank you very much. Your suggestions solved the problem. I have an additional problem with fields. This code generates compilation errors:

const field = this.block.getField("GAME_OBJECTS");
         if (this.mode)
         field.menuGenerator_=TypeUtils.getInstances(this.unitytype);             
         else field.menuGenerator_=[['self','self'],['event_source','event_source']].concat(TypeUtils.getInstances(this.unitytype));
         field.setValue(field.getOptions()[0][1]);

because field has no menuGenerator_ property and no getOptions() method

Thanks again for your help
J.

**Comment by roroettg** [comment]
In this case you probably need to cast the Object to [FieldDropdown](https://developers.google.com/blockly/reference/js/Blockly.FieldDropdown) since [getField](https://developers.google.com/blockly/reference/js/Blockly.Field) does return [Blockly.Field](https://developers.google.com/blockly/reference/js/Blockly.Field)

**Comment by fjaen** [comment]
Thanks for your quick answer. This is producing a side effect because if I import 
Blockly from 'ngx-blockly' 

to do the casting:
const field = this.block.getField("GAME_OBJECTS") as Blockly.FieldDropdown;

then another part of my code is broken:

return [this.block.getFieldValue('GAME_OBJECTS'),Blockly.Lua.ORDER_ATOMIC];
because now BLockly has no Lua property.

In my previous code Blockly was defined as 
declare var Blockly: any;

I apologize if I did not explain my problem correctly.
Best
J.

**Comment by fjaen** [comment]
I solved this by importing Blockly with an Alias
Thanks
