### ISSUE TITLE
Blockly mainWorkspace undefined

### ISSUE THREAD

**Issue by fjaen** [roroettg/ngx-blockly#82]
Hi,
I am accessing the main workspace by using
declare var Blockly: any;
...
Blockly.mainWorkspace

within the "defineBlock" method of a CustomBlock but I get an error saying this property (mainWorkspace) is undefined.

At the time I am trying to access Blockly.mainworkspace I have an active workspace because
this.block.workspace returns a valid object  and I also can see in my browser a workspace in which I can drag and drop  blocks

Does any one know what the problem might be?
Thank you very much

**Comment by fjaen** [comment]
In fact the problem is that "Blockly" is not instantiated when I access Blockly.mainWorkspace

**Comment by IBlackI** [comment]
The blockly is no longer a global, but is exported. So you can import it from ngx-blockly and use it. e.g. 
![image](https://user-images.githubusercontent.com/4059637/155691640-d3571fb7-182e-4856-8bee-4482f4e7415d.png)

**Comment by fjaen** [comment]
ok! I understand. Many things have changed.
Then, how do I have access now the Lua property? It seems is not there anymore

Blockly.Lua.valueToCode(...)
Blockly.Lua.ORDER_ATOMIC

I have also realized that now a block created with the workspace does not have methods initSvg or render nor a blockInstance property. Please, do you know how is this done now?

auxBlock.blockInstance.setConcreteInstancesOnly(false);
auxBlock.initSvg();
auxBlock.render();

Many thanks again for your great help

**Comment by IBlackI** [comment]
I do not have an answer regarding the lua.
As for the initSvg, the return of new workspace block is a Blockly.Block, but only Blockly.BlockSvg have that methods. So you will need to tell typescript it is an BlockSvg like this:
![image](https://user-images.githubusercontent.com/4059637/155698152-b91850ee-a249-4fb2-b659-50edc5fbe5b4.png)

**Comment by fjaen** [comment]
Thank you veru much. It is weird that the exported Blockly does not expose a Javascript or  a Lua property to generate code. In the examples provided in the Blockly documentation they use Blockly.Javascript.valueToCode(...). I am a bit lost now :-( because I cannot generate code from custom blocks.

**Comment by roroettg** [comment]
Unfortunately the latest changes to Blockly made that approach incompatible with typescript. To access Generators do it like this:

`Blockly[NgxBlocklyGenerator.LUA].valueToCode()` or `Blockly['Lua'].valueToCode()`

**Comment by fjaen** [comment]
Thank you very much! It works!
