### ISSUE TITLE
Code generator limitation

### ISSUE THREAD

**Issue by aurimasko** [roroettg/ngx-blockly#86]
Hi, I faced a problem. Lets say I want to create a block which can contain other block.

How should I generate the code for this block?
 I cant know what exact block was added to it cause different options can be used.

Original blockly has "valueToCode" and "statementToCode" methods.. Can I somehow use them in code generation method in ngx-blockly?

**Comment by roroettg** [comment]
Hi,

it is possible to use these methods.

Adapt the following code to your needs:
```
Blockly[NgxBlocklyGenerator.PYTHON].valueToCode(block, 'VALUE', Blockly.JavaScript.ORDER_MEMBER));
Blockly['Python'].valueToCode(block, 'VALUE', Blockly.JavaScript.ORDER_MEMBER));
```

**Comment by aurimasko** [comment]
Thank you very much!
