### ISSUE TITLE
Cannot read property 'workspaceToCode' of undefined

### ISSUE THREAD

**Issue by candy4290** [roroettg/ngx-blockly#9]
ngx-blockly version: 0.0.45
![101574071287_ pic](https://user-images.githubusercontent.com/19907991/69043157-7b7fca80-0a2d-11ea-911f-a85cd015569c.jpg)
write follow the readme.md, but when i use NgxBlocklyGeneratorConfig, error occured

**Comment by candy4290** [comment]
> ngx-blockly version: 0.0.45
> ![101574071287_ pic](https://user-images.githubusercontent.com/19907991/69043157-7b7fca80-0a2d-11ea-911f-a85cd015569c.jpg)
> write follow the readme.md, but when i use NgxBlocklyGeneratorConfig, error occured

solved!
reason: lack scripts
angular.json  "scripts": [
              "node_modules/ngx-blockly/scripts/blockly/blockly_compressed.js",
              "node_modules/ngx-blockly/scripts/blockly/blocks_compressed.js",
              "node_modules/ngx-blockly/scripts/blockly/python_compressed.js",
              "node_modules/ngx-blockly/scripts/blockly/javascript_compressed.js",
              "node_modules/ngx-blockly/scripts/blockly/php_compressed.js",
              "node_modules/ngx-blockly/scripts/blockly/dart_compressed.js",
              "node_modules/ngx-blockly/scripts/blockly/lua_compressed.js",
              "node_modules/ngx-blockly/scripts/blockly/msg/js/en.js"
            ]

**Comment by fjaen** [comment]
Hello, 
I also have this problem.
My angular.json scripts are 
"scripts": [                  
              "node_modules/ngx-blockly/scripts/blockly/blockly_compressed.js",
              "node_modules/ngx-blockly/scripts/blockly/blocks_compressed.js",
              "node_modules/ngx-blockly/scripts/blockly/msg/js/en.js",
              "node_modules/ngx-blockly/scripts/blockly/lua_compressed.js",
              "node_modules/ngx-blockly/scripts/blockly/python_compressed.js",
              "node_modules/ngx-blockly/scripts/blockly/javascript_compressed.js",
              "node_modules/ngx-blockly/scripts/blockly/php_compressed.js",
              "node_modules/ngx-blockly/scripts/blockly/dart_compressed.js"              
            ]
my html  is
<div class="container">
  <ngx-blockly [config]="config" [customBlocks]="customBlocks" [generatorConfig]="generatorConfig" (javascriptCode)="onCode($event)" (luaCode)="onCode($event)"></ngx-blockly>
</div>

and my generatorConfig is
  public generatorConfig: NgxBlocklyGeneratorConfig = {
    javascript:true,
    lua:true
};

In my custom block class the method 
toJavaScriptCode(block: CustomBlock): string | any[]  is corrrectly called but

the method toLuaCode(block: CustomBlock): string | any[] is never called

Instead  a TypeError is generated 
stack: "TypeError: Cannot read property 'workspaceToCode' of undefined
    at NgxBlocklyComponent.workspaceToCode (http://localhost:4200/vendor.js:53873:43)
    at NgxBlocklyComponent._onWorkspaceChange (http://localhost:4200/vendor.js:53992:14)
    at Blockly.WorkspaceSvg.Blockly.Workspace.fireChangeListener (http://localhost:4200/scripts.js:357:447)
    at Blockly.Events.fireNow_ (http://localhost:4200/scripts.js:58:220)
    at timer (http://localhost:4200/polyfills.js:11942:41)
    at ZoneDelegate.invokeTask (http://localhost:4200/polyfills.js:9787:31)
    at Object.onInvokeTask (http://localhost:4200/vendor.js:39541:33)
    at ZoneDelegate.invokeTask (http://localhost:4200/polyfills.js:9786:60)
    at Zone.runTask (http://localhost:4200/polyfills.js:9559:47)
    at invokeTask (http://localhost:4200/polyfills.js:9868:34)"

Am I missing anything? Thanks for your help
