### ISSUE TITLE
Custom generator and blocks

### ISSUE THREAD

**Issue by savelkouls** [roroettg/ngx-blockly#93]
Hello,

I did some searching on the issues because I couldn't imagine nobody has had this issue before, and it seems I already found out it should be possible but I have no clue how to implement it.
I followed the official documentation on building blockly ( https://developers.google.com/blockly/guides/modify/web/building ) and I have "***_compressed.js" files that work in HTML and vanilla js. 

My question is how (where) to put these files.
I do not have a path like "node_modules/ngx-blockly/scripts/blockly/javascript_compressed.js", as mentioned in most of the issues that have been resolved.

Hope you could give me a headstart.

**Comment by roroettg** [comment]
Hi,

I have currently only my Phone available.

For what exactly do you need a headstart? A general how to start is this.

https://roroettg.github.io/ngx-blockly/basic/index.html

Custom-Blocks
https://github.com/roroettg/ngx-blockly#custom-block

Custom-Generator
I will come back later to this.

**Comment by savelkouls** [comment]
I was hoping it would be possible to use my existing generator, a robotframework_compressed.js file. 
and the corresponding blocks in blocks_compressed.js which are based on the blockly JSON blocks format.

But reading through the link you provided I think I should rewrite everything to generate 800+ new CustomBlock classes.

**Comment by savelkouls** [comment]
I managed to get my desired installation working.
I think the main reason why things did not go smoothly was becasue here on github the first step of the installation was missing, but I found it on the NPM package page.

Adding blockly to the scripts: [ ] in angular.json
