### ISSUE TITLE
How to import custom block into built-in Category

### ISSUE THREAD

**Issue by orlenkoo** [roroettg/ngx-blockly#95]
Hi, 
Thanks for reviewing my issue.
I am going to import new custom module into built-in category.
```  public customBlocks: CustomBlock[] = [new TriggerBlock(), new StateBlock(), new ActionBlock()];
  public triggerBlocks: CustomBlock[] = [new TriggerBlock()];
  public actionBlocks: CustomBlock[] = [new ActionBlock()];
  public stateBlocks: CustomBlock[] = [new StateBlock()];

  constructor(
    private functionsService: FunctionsService,
    private route: ActivatedRoute,
    private messagingService?: MessagingService,
    
  ) {
    const workspace = new Blockly.WorkspaceSvg(new Blockly.Options({}));
    const functionsToolbox: NgxBlocklyToolbox = new NgxBlocklyToolbox(workspace);
    
    functionsToolbox.nodes = [
      LOGIC_CATEGORY,
      LOOP_CATEGORY,
      MATH_CATEGORY,
      TEXT_CATEGORY,
      new Separator(),
      new Category("Variables", "#00ff00", [VARIABLES_CATEGORY, ...this.stateBlocks]),
      new Category("Triggers", "#ff0000", [
        ...this.triggerBlocks,
      ]),
      new Category("Actions", "#0000ff", [
        ...this.actionBlocks,
      ]),
    ];

    this.functionsConfig.toolbox = functionsToolbox.toXML();
  }

  async ngOnInit() {
    await this.getFunctions();
    this.subscription = this.messagingService.messages.subscribe((msg) => {```

In the above code, I am going to import StateBlock into built-in `VARIABLES_CATEGORY`..
So I tried this and it looks like below, but it is not desired result.

```new Category("Variables", "#00ff00", [VARIABLES_CATEGORY, ...this.stateBlocks]),```

![image](https://user-images.githubusercontent.com/100224661/197156025-9bc9b0b1-cc79-4e1a-aedd-4e22cd4dd0e9.png)


It should look like this:

![image](https://user-images.githubusercontent.com/100224661/197158247-23279f58-69da-42c5-9b64-b67df0dc4c15.png)

Can you help?

**Comment by roroettg** [comment]
Hi,
can you elaborate what you are trying to achieve?

In your example everything works as intended, since you are adding a category to a category, which makes VARIABLES_CATEGORY a subcategory. 

Are you trying to create predefined variables or why are you trying to add a block to the variables category?

**Comment by orlenkoo** [comment]
Hello, @roroettg 
Thanks for your response.

**Are you trying to create predefined variables or why are you trying to add a block to the variables category?**

Yes, I am trying to inject custom block into predefined category.
The reason is why the client is asking like that look.

In my code, the category was added into category. This is not what I am looking for.
I want to inject my custom block into predefined categories in ngx-blockly such as LOGIC_CATEGORY, LOOP_CATEGORY, MATH_CATEGORY, TEXT_CATEGORY, VARIABLES_CATEGORY..

I think it is possible with adding or removing block in xml config.

```toolbox: '<xml id="toolbox" style="display: none">' +
                    '<block type="controls_if"></block>' +
                    '<block type="controls_repeat_ext"></block>' +
                    '<block type="logic_compare"></block>' +
                    '<block type="math_number"></block>' +
                    '<block type="math_arithmetic"></block>' +
                    //'<block type="text"></block>' +
                    '<block type="text_print"></block>' +
                    '<block type="state_block"></block>' +
                 '</xml>',```

But I want to know the way to generate toolbox like this.

```functionsToolbox.nodes = [
      LOGIC_CATEGORY,
      LOOP_CATEGORY,
      MATH_CATEGORY,
      TEXT_CATEGORY,
      new Separator(),
      new Category("Variables", "#00ff00", [VARIABLES_CATEGORY, ...this.stateBlocks]),```

Is there a solution?

**Comment by roroettg** [comment]
In general this is possible. So for example you could do this.

`LOGIC_CATEGORY.nodes.push(...this.stateBlocks);`

However variable and procedure category are different, since they are dynamic categories. Everytime you open one of them they are populated.

https://developers.google.com/blockly/guides/configure/web/toolbox#dynamic_categories

Adding variables is possible at runtime like this.

`workspace.createVariable('Name', null, null);`

**Comment by orlenkoo** [comment]
Hello, Thanks for your kind  note.

`    LOGIC_CATEGORY.nodes.push(...this.stateBlocks);
`
This is working well.

But this is not working.

`VARIABLES_CATEGORY.nodes.push(...this.stateBlocks);
`

**Comment by roroettg** [comment]
Please read the second part of my message. 

Variable and Procedure category work differently. They are filled everytime the category is opened. For example the variable category gets populated from a global variable list. Your blocks are not part of this list, that is why they are never shown. 

If you want to initialize the category with sth. like default variables, you can use the `createVariable()` method from my previous comment.

**Comment by orlenkoo** [comment]
Yeah.. It is worked.
Thanks very much.
