### ISSUE TITLE
Unknown block type: ActionBlock  - when use several custom blocks in different categories.

### ISSUE THREAD

**Issue by orlenkoo** [roroettg/ngx-blockly#97]
I am going to use 3 custom blocks(triggerblock, actionblock, stateblock) in 3 new categories.

Here are code:

 - functions.component.ts
    
```
import { TriggerBlock } from "./blocks/trigger.block";
import { StateBlock } from "./blocks/state.block";
import { ActionBlock } from "./blocks/action.block";

.....
  public functionsConfig: NgxBlocklyConfig = {
    trashcan: false,
    generators: [NgxBlocklyGenerator.JAVASCRIPT],
    defaultBlocks: true,
    move: {
      scrollbars: true,
      wheel: true,
    },
  };
  public triggerBlocks: CustomBlock[] = [new TriggerBlock(this.deviceResponse)];
  public actionBlocks: CustomBlock[] = [new ActionBlock()];
  public stateBlocks: CustomBlock[] = [new StateBlock()];
  public customBlocks: CustomBlock[] = [
    ...this.triggerBlocks,
    ...this.actionBlocks,
    ...this.stateBlocks,
  ];

.........

  constructor(
    private functionsService: FunctionsService,
    private deviceService: DeviceService,
    private route: ActivatedRoute,
    private messagingService?: MessagingService
  ) {
    const workspace = new Blockly.WorkspaceSvg(new Blockly.Options({}));
    const functionsToolbox: NgxBlocklyToolbox = new NgxBlocklyToolbox(
      workspace
    );

    functionsToolbox.nodes = [
      LOGIC_CATEGORY,
      LOOP_CATEGORY,
      MATH_CATEGORY,
      TEXT_CATEGORY,
      new Separator(),
      VARIABLES_CATEGORY,
      FUNCTIONS_CATEGORY,
      // new Category("Variables", "#00ff00", [VARIABLES_CATEGORY, ...this.stateBlocks]),
      new Category("Triggers", "#ff0000", [...this.triggerBlocks]),
      new Category("Actions", "#0000ff", [...this.actionBlocks]),
    ];

    this.functionsConfig.toolbox = functionsToolbox.toXML();
  }
```

- trigger.block.ts
  
```
 import { Blockly, CustomBlock, BlockMutator } from "ngx-blockly";

export class TriggerBlock extends CustomBlock {
  deviceResponse = [];
  constructor(...args: any[]) {
    // Add Mutator or further args if needed
    super("TriggerBlock", ...args);
    this.class = TriggerBlock;
    this.deviceResponse = this.args[0];
  }
  
  defineBlock() {
    this.block
      .appendDummyInput()
      .appendField("DeviceResponse")
      .appendField(new Blockly.FieldDropdown(this.generateLists()), 'LABEL');
      // .appendField(new Blockly.FieldImage(this.args[0], 50, 50, "*"));
    this.block.setOutput(true, "Input");
    this.block.setColour(30);
    this.block.setTooltip("trigger");
    this.block.setHelpUrl("");
  }

  generateLists() {
    let lists = [];
    this.deviceResponse.forEach(ele=> {
      lists.push([ele.name, ele.id]);
      ele.responses.forEach(response=>{
        lists.push(['  -  ' + response.name, ele.name + String.fromCharCode(1) + response.name + String.fromCharCode(1) + response.id ]);
      })
    })
    return lists;   
  }
```

- action.block.ts
   
....
```
import { Blockly, CustomBlock } from "ngx-blockly";

export class ActionBlock extends CustomBlock {
    constructor() {
      // Add Mutator or further args if needed
      super("ActionBlock");
      this.class = ActionBlock;
    }
  
    defineBlock() {
      this.block
        .appendDummyInput()
        .appendField("Device Command")
        // .appendField(new Blockly.FieldImage("assets/testblock.png", 50, 50, "*"))
        // .appendField(new Blockly.FieldImage(this.args[0], 50, 50, "*"));
      this.block.setOutput(true, "Input");
      this.block.setColour(30);
      this.block.setTooltip("action");
      this.block.setHelpUrl("");
    }
  

```
- functions.component.html
  
```
<ngx-blockly
                    [config]="functionsConfig"
                    (javascriptCode)="onCode($event)"
                    [customBlocks]="customBlocks"
                    class="blockly-workspace"
                  ></ngx-blockly>
```

But I got this error:
 
ERROR TypeError: Unknown block type: ActionBlock

The `triggerblock` is working well. But ActionBlock is not working.

![Untitled](https://user-images.githubusercontent.com/100224661/198213140-d1c5c49c-4840-4408-a840-a0d239042c6a.png)

And here, when I change the type name of triggerblock like from TriggerBlock to TestTest, it threw error.

ERROR TypeError: Unknown block type: TriggerBlock

```
constructor(...args: any[]) {
    // Add Mutator or further args if needed
    super("TriggerBlock", ...args);  => super("TestTest", ...args);
```

**Comment by orlenkoo** [comment]
This error occured after I add args into triggerblock. Before it worked.

**Comment by roroettg** [comment]
Hi,

please look at the constructor of CustomBlock, second argument needs to be a BlockMutator

Change `super("TriggerBlock", ...args);` to `super("TriggerBlock", null, ...args);`

**Comment by orlenkoo** [comment]
I have changed like this:

- functions.component.ts
 
`    public triggerBlocks: CustomBlock[] = [new TriggerBlock("TriggerBlock", null, this.deviceResponse)];
`
- triggers.block.ts

```
 constructor(type: string, blockMutator: BlockMutator, ...args: any[]) {
    // Add Mutator or further args if needed
    super(type, blockMutator, ...args);
    this.class = TriggerBlock;
```

And it worked..

But it throws error when I change the type name of TriggerBlock like this.

`public triggerBlocks: CustomBlock[] = [new TriggerBlock("TestTest", null, this.deviceResponse)];
`
Unknown Block Type TriggerBlock


Should I use only same name of custom block like "TriggerBlock"?


And when I add 4 parameters in constructor, I can not read args[0].

```
....
public triggerBlocks: CustomBlock[] = [new TriggerBlock("TriggerBlock", null, null, this.deviceResponse)];

.......
constructor(type: string, block: any, blockMutator: BlockMutator, ...args: any[]) {
    // Add Mutator or further args if needed
    super(type, block, blockMutator, ...args);
```

And then here, args[0] should be this.deviceResponse, but it is null..

This error occurs when I use both of block, blockMutator together.
And If I use one of them, it works..

Can you explain about this?

**Comment by roroettg** [comment]
You should able to chose a name you like as long as it is unique. 3 parameter should be the right way. 

I am not seeing any issue at the moment.

Could you provide a complete example stackblitz or provide a link to repository?

**Comment by orlenkoo** [comment]
You can check this.

https://codesandbox.io/s/ngx-blockly-custom-block-categories-forked-wrjgze

 I have added like this.

app.component.ts
...
` public customBlocks: CustomBlock[] = [new ExampleBlock("examplgggblock", null, null, [{key:"test"}])];
`....

This is example.block.ts

```
import { Blockly, CustomBlock, BlockMutator} from "ngx-blockly";

export class ExampleBlock extends CustomBlock {
  constructor(type: string, block:any, blockMutator: BlockMutator,  ...args: any[]) {
    super(type, block, blockMutator, ...args);
    this.class = ExampleBlock;
  }

  public defineBlock() {
    this.block.appendDummyInput().appendField(this.args[0][0].key)
    .appendField(this.type);
  }

  public toPythonCode(block: Blockly.Block): string | any[] {
    return "";
  }
}

```

Here, when select bla category, it threw error.

ERROR TypeError: Cannot read properties of null (reading '0')

It seems like that [{key:"test"}] is not input into args[0].
If we use one of block, blockmutator, it works.
But we use both of them ,it does not work.

**Comment by roroettg** [comment]
If you look at args, it has two elements. The second element is the object you are passing.
Using should work `this.args[1].key`.

This is not the intended behavior and is probably a bug. I will look deeper into his.

**Comment by roroettg** [comment]
Ok, I found the issue there is no bug.

https://codesandbox.io/s/ngx-blockly-custom-block-categories-forked-wrjgze?file=/src/app/blocks/example.block.ts

The block argument you had in the constructor is unnecessary. This way you always gave too many arguments and this.args[0] pointed to a null, which was your third argument.

```typescript
 public customBlocks: CustomBlock[] = [
    new ExampleBlock("examplgggblock", null, [{ key: "test" }])
  ];
```

```typescript
constructor(type: string, blockMutator: BlockMutator,  ...args: any[]) {
    super(type, blockMutator, ...args);
    this.class = ExampleBlock;
  }
```

**Comment by orlenkoo** [comment]
Yeah, that is working.
I removed block argument, it works well.
Thanks very much.
