### ISSUE TITLE
How to make custom block from built-in block in FUNCTIONS_CATEGORY

### ISSUE THREAD

**Issue by orlenkoo** [roroettg/ngx-blockly#98]
Hello, 
Hope you are doing well..
I am going to make custom block from the first block(to do something block) of FUNCTIONS_CATEGORY with dropdown.
That is, I am going to input dropdown list into the first block of FUNCTIONS_CATEGORY instead "do something".

Just like this image: 

![1](https://user-images.githubusercontent.com/100224661/198227444-6719d020-e758-4123-acc2-f817792b8d0f.png)

Like this code:
 
```
defineBlock() {
    this.block
      .appendDummyInput()
      .appendField("DeviceResponse")
      .appendField(FUNCTIONS_CATEGORY.nodes[0], new Blockly.FieldDropdown())
      .appendField(new Blockly.FieldDropdown(this.generateLists()), 'LABEL');
```

Is that possible?

One more question:

Is there a dictionary shows all built-in blocks' types of built-in categories like math_number, logic_boolean, controls_for...because I don't know the type of first block in FUNCTIONS_CATEGORY?

Thanks.

**Comment by roroettg** [comment]
I am not sure if I understand correctly what you are trying to do.

You want to create a Block with a dropdown, that is filled by you?
Why do you want to use a function block for that?

Dropdowns can be used as decribed in the blockly docu.

https://developers.google.com/blockly/guides/create-custom-blocks/fields/built-in-fields/dropdown#javascript

As far as I know there is currently no way to get all blocks.

A list of types can be seen here, there might be missing some which I have not yet updated.

https://github.com/roroettg/ngx-blockly/blob/master/projects/ngx-blockly/src/lib/ngx-blockly/models/category.ts#L128

**Comment by roroettg** [comment]
You should be able to get all existing block types from 
```
Blockly.Blocks
Blockly.Blocks['TYPE']
```

**Comment by orlenkoo** [comment]
Well, I was going to make custom block from existing block(<block type="procedures_defnoreturn") of functions category.
Just wanted to know how to get this block with code.

**Comment by roroettg** [comment]
https://github.com/google/blockly/blob/develop/blocks/procedures.js

You could probably override the existing definition of the block.

```typescript
blocks['procedures_defnoreturn'] = {
  ...PROCEDURE_DEF_COMMON,
  /**
   * Block for defining a procedure with no return value.
   * @this {Block}
   */
  init: function() {
    const initName = Procedures.findLegalName('', this);
    const nameField = new FieldTextInput(initName, Procedures.rename);
    nameField.setSpellcheck(false);
    this.appendDummyInput()
        .appendField(Msg['PROCEDURES_DEFNORETURN_TITLE'])
        .appendField(nameField, 'NAME')
        .appendField('', 'PARAMS');
    this.setMutator(new Mutator(['procedures_mutatorarg'], this));
    if ((this.workspace.options.comments ||
         (this.workspace.options.parentWorkspace &&
          this.workspace.options.parentWorkspace.options.comments)) &&
        Msg['PROCEDURES_DEFNORETURN_COMMENT']) {
      this.setCommentText(Msg['PROCEDURES_DEFNORETURN_COMMENT']);
    }
    this.setStyle('procedure_blocks');
    this.setTooltip(Msg['PROCEDURES_DEFNORETURN_TOOLTIP']);
    this.setHelpUrl(Msg['PROCEDURES_DEFNORETURN_HELPURL']);
    this.arguments_ = [];
    this.argumentVarModels_ = [];
    this.setStatements_(true);
    this.statementConnection_ = null;
  },
  /**
   * Return the signature of this procedure definition.
   * @return {!Array} Tuple containing three elements:
   *     - the name of the defined procedure,
   *     - a list of all its arguments,
   *     - that it DOES NOT have a return value.
   * @this {Block}
   */
  getProcedureDef: function() {
    return [this.getFieldValue('NAME'), this.arguments_, false];
  },
  callType_: 'procedures_callnoreturn',
};
```
If you use **procedures_defnoreturn** as type you should be able to overwrite the init-part for example, by your own defineBlock code.

**Comment by orlenkoo** [comment]
Yeah, this is really good solution.
Thanks very much.
