### ISSUE TITLE
Custom Block -  Is it possible to define twice in one component?

### ISSUE THREAD

**Issue by orlenkoo** [roroettg/ngx-blockly#99]
Hello,  

Hope you are doing well.

I am going to define custom block after get Responsedata from back-end side in ngOnInit.

So, after get deviceResponse from api call, I am going to put triggerBlocks into pre-defined custom-block.
So I tried like this code: But it does not work. 

....
 
```
 this.deviceResponse = [];
 public triggerBlocks: CustomBlock[] = [];
```

......

```
async ngOnInit() {
    await this.getFunctions();
    await this.getDevices(){
      this.deviceResponse = await this.deviceService.get();
    };
    this.triggerBlocks = [new TriggerBlock("TriggerBlock", null, this.deviceResponse)];
```

The Triggers Category is blank.
....

```
   functionsToolbox.nodes = [
      LOGIC_CATEGORY,
      LOOP_CATEGORY,
      MATH_CATEGORY,
      TEXT_CATEGORY,
      new Separator(),
      VARIABLES_CATEGORY,
      FUNCTIONS_CATEGORY,
      // new Category("Variables", "#00ff00", [VARIABLES_CATEGORY, ...this.stateBlocks]),
      new Category("Triggers", "#ff0000", [...this.triggerBlocks]),
      new Category("Actions", "#0000ff", [...this.actionBlocks]),
    ];
....
```

Can you help, please?

Thanks very much.

**Comment by roroettg** [comment]
When you are creating the toolbox, Triggerblock does not exist and the category is empty. 

You could create the toolbox or workspace after your request to the api has finished.

**Comment by orlenkoo** [comment]
Yeah, I have created toolbox after get response from api instead declaring it in constructor.
And it works.
Thanks so much.
